# This workflow will install pgvector docker image, Python dependencies, run tests

name: docling_pgvector_test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      pgvector:
        image: pgvector/pgvector:pg17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vectordb
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: check running containers state
        run: docker ps
        
      - name: Check available images
        run: docker images

      - name: Install postgres client tools required for psql command
        run: sudo apt-get install -y postgresql-client

      - name: Create vectordb database
        run: |
            PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres \
            -c "CREATE DATABASE vectordb;" || echo "DB already exists, continuing..."
            
            PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d vectordb \
            -c "CREATE EXTENSION IF NOT EXISTS vector;"

      - name: Verify database and extension
        run: |
          # check database exists
          PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres \
            -c "SELECT datname FROM pg_database WHERE datname='vectordb';" \
            | grep vectordb && echo "vectordb exists" || exit 1

      - name: Install uv
        uses: astral-sh/setup-uv@v7        # official uv action
        with:
          enable-cache: true               # caches deps between runs
          python-version: "3.12"

      - name: Install all dependencies
        run: uv sync                        # reads pyproject.toml + uv.lock
        
      - name: Install all project in editable mode
        run: uv pip install -e .
        
      - name: Download test PDF
        run: |
          mkdir -p ./data
          curl -L https://arxiv.org/pdf/2408.09869 -o ./data/test.pdf
          ls -la ./data/
      
      - name: Check if import works
        run: uv run python -c "from pgvector_client import PGVectorClient; print('Import OK')"

      - name: Run pytest 
        run: uv run pytest test/pgpytest.py -v -s
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vectordb
        
